#tag_Name_asg.yaml
ansible_ssh_user: "ec2-user"
ansible_ssh_private_key_file: ~/.ssh/asg
proxy_ssh_key: ~/.ssh/bastion
ansible_ssh_common_args: >-
  -o ProxyCommand="ssh 
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null
  -o ServerAliveInterval=5
  -W %h:%p
  -i {{ proxy_ssh_key }}
  -q {{ ansible_ssh_user }}@{{ hostvars[groups["_bastion"][0]]["public_ip_address"] }}"
